@startuml(id=Customer)
title Online sales system - System Context

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
left to right direction
skinparam rectangle<<44>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<2>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<3>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<48>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
rectangle "==Admin\n<size:10>[Person]</size>\n\nSales site management" <<2>> as 2
rectangle "==Customer\n<size:10>[Person]</size>\n\nCustomers with website accounts" <<1>> as 1
rectangle "==Message system\n<size:10>[Software System]</size>\n\nInformation of bills" <<48>> as 48
rectangle "==Online sales system\n<size:10>[Software System]</size>\n\nCustomers visit the website to view products or make purchases Admin will manage and update the website." <<3>> as 3
rectangle "==Transportation system\n<size:10>[Software System]</size>\n\nDeliver shoes to customers" <<44>> as 44
2 .[#707070,thickness=2].> 3 : "Login"
1 .[#707070,thickness=2].> 3 : "Register or Login"
3 .[#707070,thickness=2].> 48 : "Sends"
3 .[#707070,thickness=2].> 44 : "Sends"
@enduml