@startuml(id=Onlinesalessystem-Container)
title Online sales system - Containers

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}
hide stereotype
left to right direction
skinparam rectangle<<45>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<1>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam database<<35>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam rectangle<<2>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}
skinparam rectangle<<4>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<9>> {
  BackgroundColor #dddddd
  FontColor #000000
  BorderColor #9a9a9a
}
skinparam rectangle<<41>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
rectangle "==Admin\n<size:10>[Person]</size>\n\nSales site management" <<2>> as 2
rectangle "==Customer\n<size:10>[Person]</size>\n\nCustomers with website accounts" <<1>> as 1
rectangle "==Message system\n<size:10>[Software System]</size>\n\nInformation of bills" <<45>> as 45
rectangle "==Transportation system\n<size:10>[Software System]</size>\n\nDeliver shoes to customers" <<41>> as 41
package "Online sales system\n[Software System]" {
  rectangle "==API Application\n<size:10>[Container: ASP.NET core and C#]</size>\n\nUse it for the back-end" <<9>> as 9
  database "==Database\n<size:10>[Container: SQL server 2019]</size>\n\nStore products, customers, bills" <<35>> as 35
  rectangle "==Web Application\n<size:10>[Container: JS and VueJs]</size>\n\nDelivers the static content of shoes website" <<4>> as 4
}
9 .[#707070,thickness=2].> 35 : "Reads from and writes to"
9 .[#707070,thickness=2].> 45 : "Sends"
9 .[#707070,thickness=2].> 41 : "Sends"
2 .[#707070,thickness=2].> 4 : "Login"
1 .[#707070,thickness=2].> 4 : "Register or Login"
4 .[#707070,thickness=2].> 9 : "Make API calls to"
@enduml